/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
import org.hamcrest.CoreMatchers.`is`
import org.hamcrest.MatcherAssert.assertThat
import org.hamcrest.Matchers.equalTo
import kotlin.test.Test

class FrequencySummerTest {
    /**
     * +1, +1, +1 results in  3
     */
    @Test fun allPositive() {
        val classUnderTest = FrequencySummer()
        val list = listOf(+1, +1, +1)
        assertThat(classUnderTest.sum(list), `is`(equalTo(3)))
    }

    /**
     * +1, +1, -2 results in  0
     */
    @Test fun mixedSign() {
        val classUnderTest = FrequencySummer()
        val list = listOf(+1, +1, -2)
        assertThat(classUnderTest.sum(list), `is`(equalTo(0)))
    }

    /**
     * -1, -2, -3 results in -6
     */
    @Test fun allNegative() {
        val classUnderTest = FrequencySummer()
        val list = listOf(-1, -2, -3)
        assertThat(classUnderTest.sum(list), `is`(equalTo(-6)))
    }
}
